apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dvdq9zpag-python 
  janus-idp.io/tekton: dvdq9zpag-python
  backstage.io/kubernetes-id: dvdq9zpag-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dvdq9zpag-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  