apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dvdq9zpag-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dvdq9zpag-python 
  name: dvdq9zpag-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dvdq9zpag-python 
